import { describe,expect,it,vi } from "vitest";
import { RealPerplMarketDataSource } from "../../../src/adapters/perpl/PerplMarketDataSource.js";
class Socket {readyState=1;sent:string[]=[];listeners=new Map<string,(e:{data?:unknown})=>void>();addEventListener(t:string,f:(e:{data?:unknown})=>void){this.listeners.set(t,f);}send(v:string){this.sent.push(v);}close(){this.listeners.get("close")?.({});}open(){this.listeners.get("open")?.({});}}
const context={markets:[{market_id:"m9",symbol:"BTC-PERP",price_decimals:2,size_decimals:3,minimum_posting_size:"1",is_open:true}]};
const response={ok:true,status:200,json:async()=>context} as Response;
describe("RealPerplMarketDataSource",()=>{
  it("uses only public context, dynamically subscribes in one batch, and sends no ping",async()=>{const socket=new Socket();const fetchMock=vi.fn(async()=>response) as unknown as typeof fetch;const source=new RealPerplMarketDataSource("https://local.invalid","ws://local",1000,fetchMock,()=>socket,()=>1000,()=>.5);expect((await source.getMarkets())[0]?.marketId).toBe("m9");const pending=source.connect(["m9"]);socket.open();await pending;expect(socket.sent).toHaveLength(1);expect(socket.sent[0]).toContain("market-state");expect(socket.sent[0]).not.toMatch(/ping/i);});
  it("fails closed on incomplete, crossed, stale, and sequence-gapped books",async()=>{let now=1000;const socket=new Socket();const source=new RealPerplMarketDataSource("https://local.invalid","ws://local",10,async()=>response,()=>socket,()=>now,()=>.5);await source.getMarkets();const pending=source.connect(["m9"]);socket.open();await pending;expect(()=>source.getOrderBook("m9")).toThrow(/incomplete/);expect(()=>source.ingest({channel:"order-book",market_id:"m9",sequence:1,timestamp:1,data:{bids:[[10000,1]],asks:[[10000,1]]}})).toThrow(/crossed/);source.ingest({channel:"order-book",market_id:"m9",sequence:2,timestamp:1,data:{bids:[[9999,1]],asks:[[10000,1]]}});now=2000;expect(()=>source.getOrderBook("m9")).toThrow(/stale/);expect(()=>source.ingest({channel:"order-book",market_id:"m9",sequence:4,timestamp:2,data:{bids:[[9999,1]],asks:[[10000,1]]}})).toThrow(/gap/);});
  it("enforces the sixteen-subscription cap",async()=>{const source=new RealPerplMarketDataSource("https://local.invalid","ws://local",10,async()=>({ok:true,status:200,json:async()=>({markets:Array.from({length:5},(_,i)=>({...context.markets[0],market_id:String(i),symbol:`M${i}`}))})}) as Response,()=>new Socket());await source.getMarkets();await expect(source.connect(["0","1","2","3","4"])).rejects.toThrow(/16/);});
});
