import { describe,expect,it,vi } from "vitest";
import { PERPL_MARKET_DATA_WS_URL, PERPL_REST_BASE_URL, RealPerplMarketDataSource } from "../../../src/adapters/perpl/PerplMarketDataSource.js";
class Socket {readyState=1;sent:string[]=[];listeners=new Map<string,(e:{data?:unknown})=>void>();addEventListener(t:string,f:(e:{data?:unknown})=>void){this.listeners.set(t,f);}send(v:string){this.sent.push(v);}close(){this.listeners.get("close")?.({});}open(){this.listeners.get("open")?.({});}}
const context={markets:[{market_id:"m9",symbol:"",name:"BTC",config:{price_decimals:2,size_decimals:3,min_posting_amount:"0",is_open:true}}]};
const response={ok:true,status:200,json:async()=>context} as Response;
describe("RealPerplMarketDataSource",()=>{
  it("uses the official public endpoints",()=>{expect(PERPL_REST_BASE_URL).toBe("https://app.perpl.xyz/api");expect(PERPL_MARKET_DATA_WS_URL).toBe("wss://app.perpl.xyz/ws/v1/market-data");});
  it("maps nested context metadata with the first non-empty symbol or name",async()=>{const fetchMock=vi.fn<(input:string|URL|Request,init?:RequestInit)=>Promise<Response>>(async()=>response);const source=new RealPerplMarketDataSource("https://local.invalid/api","ws://local",1000,fetchMock as unknown as typeof fetch,()=>new Socket());expect(await source.getMarkets()).toEqual([{marketId:"m9",symbol:"BTC",priceDecimals:2,sizeDecimals:3,minimumPostingSize:0,open:true}]);expect(String(fetchMock.mock.calls[0]?.[0])).toBe("https://local.invalid/api/v1/pub/context");});
  it("dynamically subscribes in one batch and sends no ping",async()=>{const socket=new Socket();const source=new RealPerplMarketDataSource("https://local.invalid/api","ws://local",1000,async()=>response,()=>socket,()=>1000,()=>.5);await source.getMarkets();const pending=source.connect(["m9"]);socket.open();await pending;expect(socket.sent).toHaveLength(1);expect(socket.sent[0]).toContain("market-state");expect(socket.sent[0]).not.toMatch(/ping/i);});
  it("uses the confirmed public candle path",async()=>{const fetchMock=vi.fn<(input:string|URL|Request,init?:RequestInit)=>Promise<Response>>(async()=>response);const source=new RealPerplMarketDataSource("https://local.invalid/api","ws://local",1000,fetchMock as unknown as typeof fetch,()=>new Socket());await source.getMarkets();fetchMock.mockResolvedValueOnce({ok:true,status:200,json:async()=>[]} as Response);await source.getCandles("m9",{interval:"60",fromMs:1000,toMs:2000});expect(String(fetchMock.mock.calls[1]?.[0])).toBe("https://local.invalid/api/v1/market-data/m9/candles/60/1000-2000");});
  it("fails closed on incomplete, crossed, stale, and sequence-gapped books",async()=>{let now=1000;const socket=new Socket();const source=new RealPerplMarketDataSource("https://local.invalid","ws://local",10,async()=>response,()=>socket,()=>now,()=>.5);await source.getMarkets();const pending=source.connect(["m9"]);socket.open();await pending;expect(()=>source.getOrderBook("m9")).toThrow(/incomplete/);expect(()=>source.ingest({channel:"order-book",market_id:"m9",sequence:1,timestamp:1,data:{bids:[[10000,1]],asks:[[10000,1]]}})).toThrow(/crossed/);source.ingest({channel:"order-book",market_id:"m9",sequence:2,timestamp:1,data:{bids:[[9999,1]],asks:[[10000,1]]}});now=2000;expect(()=>source.getOrderBook("m9")).toThrow(/stale/);expect(()=>source.ingest({channel:"order-book",market_id:"m9",sequence:4,timestamp:2,data:{bids:[[9999,1]],asks:[[10000,1]]}})).toThrow(/gap/);});
  it("enforces the sixteen-subscription cap",async()=>{const source=new RealPerplMarketDataSource("https://local.invalid","ws://local",10,async()=>({ok:true,status:200,json:async()=>({markets:Array.from({length:5},(_,i)=>({...context.markets[0],market_id:String(i),symbol:`M${i}`}))})}) as Response,()=>new Socket());await source.getMarkets();await expect(source.connect(["0","1","2","3","4"])).rejects.toThrow(/16/);});
});
