import { describe,expect,it } from "vitest";
import { PerplTradingProtocol } from "../../../src/adapters/perpl/tradingProtocol.js";

describe("PerplTradingProtocol",()=>{
  it("reuses rq for the same client id and correlates exactly once",()=>{const protocol=new PerplTradingProtocol();const rq=protocol.begin("place",{clientOrderId:"client-a"});expect(protocol.begin("place",{clientOrderId:"client-a"})).toBe(rq);protocol.markSent(rq);expect(protocol.correlate({rq,ok:true,client_order_id:"client-a",result:{orderId:"order-a"}})).toEqual({state:"confirmed",value:{orderId:"order-a"}});expect(protocol.finalize(rq)).toMatchObject({state:"confirmed"});});
  it("rejects mismatched and unknown outcomes",()=>{const protocol=new PerplTradingProtocol();const rq=protocol.begin("cancel",{orderId:"order-a"});protocol.markSent(rq);expect(()=>protocol.correlate({rq,ok:true,order_id:"order-b"})).toThrow(/mismatch/);expect(()=>protocol.correlate({rq:"999",ok:true})).toThrow(/unknown rq/);});
  it("resolves cancellation races from authoritative order state",()=>{const filled=new PerplTradingProtocol();const a=filled.begin("cancel",{orderId:"order-a"});filled.markSent(a);expect(filled.resolveCancelRace(a,{open:false,filled:true})).toEqual({state:"confirmed",value:{cancelled:false,filled:true}});const gone=new PerplTradingProtocol();const b=gone.begin("cancel",{orderId:"order-b"});gone.markSent(b);expect(gone.resolveCancelRace(b,{open:false,filled:false})).toEqual({state:"confirmed",value:{cancelled:true,filled:false}});});
  it("invalidates sequence state on gaps and marks in-flight sends ambiguous on disconnect",()=>{const protocol=new PerplTradingProtocol();protocol.connect();protocol.acceptSnapshot(10);protocol.acceptUpdate(11);expect(()=>protocol.acceptUpdate(13)).toThrow(/gap is ambiguous/);const rq=protocol.begin("place",{clientOrderId:"client-a"});protocol.markSent(rq);protocol.disconnect();expect(protocol.finalize(rq)).toEqual({state:"ambiguous",reason:"disconnected before correlated outcome"});});
  it("cursors PnL and funding by timestamp plus identity",()=>{const protocol=new PerplTradingProtocol();protocol.setPnlCursor([{id:"a",timestamp:100},{id:"b",timestamp:100}]);expect(protocol.unseenPnl([{id:"a",timestamp:100},{id:"c",timestamp:100},{id:"d",timestamp:101}])).toEqual([{id:"c",timestamp:100},{id:"d",timestamp:101}]);protocol.setFundingCursor([{id:"f1",timestamp:200}]);expect(protocol.unseenFunding([{id:"f1",timestamp:200},{id:"f2",timestamp:200}])).toEqual([{id:"f2",timestamp:200}]);});
});
