import { ExchangeAdapterError } from "../AdapterError.js";
import type { PerplAuthenticatedFrame } from "./authTypes.js";

type Row = Record<string, unknown>;
const amountPattern = /^-?\d+(?:\.\d+)?$/;
const uint64Max = 18_446_744_073_709_551_615n;

function object(value: unknown, field: string): Row {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new ExchangeAdapterError(`Perpl ${field} is malformed`);
  return value as Row;
}
function array(value: unknown, field: string): unknown[] { if (!Array.isArray(value)) throw new ExchangeAdapterError(`Perpl ${field} is malformed`); return value; }
function string(value: unknown, field: string): string { if (typeof value !== "string" || !value) throw new ExchangeAdapterError(`Perpl ${field} is malformed`); return value; }
function bool(value: unknown, field: string): boolean { if (typeof value !== "boolean") throw new ExchangeAdapterError(`Perpl ${field} is malformed`); return value; }
function safeInteger(value: unknown, field: string, maximum = Number.MAX_SAFE_INTEGER): number { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0 || value > maximum) throw new ExchangeAdapterError(`Perpl ${field} is not a safe unsigned integer`); return value; }
function uint64(value: unknown, field: string): number { const result=safeInteger(value,field); if(BigInt(result)>uint64Max) throw new ExchangeAdapterError(`Perpl ${field} exceeds uint64`); return result; }
function signedInteger(value: unknown, field: string): number { if(typeof value!=="number"||!Number.isSafeInteger(value)) throw new ExchangeAdapterError(`Perpl ${field} is not a safe integer`); return value; }
function amount(value: unknown, field: string): string { if(typeof value!=="string"||!amountPattern.test(value)) throw new ExchangeAdapterError(`Perpl ${field} is not a decimal Amount`); return value; }
function optional<T>(value: unknown, map: (item: unknown) => T): T | undefined { return value === undefined ? undefined : map(value); }
function timestamp(value: unknown, field: string): Row { const r=object(value,field); return { ...r, ...optional(r.b,(v)=>safeInteger(v,`${field}.b`))===undefined?{}:{b:safeInteger(r.b,`${field}.b`)}, ...optional(r.t,(v)=>safeInteger(v,`${field}.t`))===undefined?{}:{t:safeInteger(r.t,`${field}.t`)}, ...optional(r.tx,(v)=>safeInteger(v,`${field}.tx`))===undefined?{}:{tx:safeInteger(r.tx,`${field}.tx`)}, ...(r.txid===undefined?{}:{txid:string(r.txid,`${field}.txid`)}), ...optional(r.l,(v)=>safeInteger(v,`${field}.l`))===undefined?{}:{l:safeInteger(r.l,`${field}.l`)} }; }

function account(value: unknown): Row { const r=object(value,"account"); return { in:safeInteger(r.in,"account.in",0xffffffff), id:uint64(r.id,"account.id"), fr:bool(r.fr,"account.fr"), fw:bool(r.fw,"account.fw"), ft:safeInteger(r.ft,"account.ft",0xff), lfr:uint64(r.lfr,"account.lfr"), b:amount(r.b,"account.b"), lb:amount(r.lb,"account.lb"), ...(r.h===undefined?{}:{h:array(r.h,"account.h").map(event)}) }; }
function event(value: unknown): Row { const r=object(value,"account event"); return { at:timestamp(r.at,"event.at"), in:safeInteger(r.in,"event.in",0xffffffff), id:uint64(r.id,"event.id"), et:safeInteger(r.et,"event.et"), ...(r.m===undefined?{}:{m:safeInteger(r.m,"event.m",0xffffffff)}), ...(r.r===undefined?{}:{r:uint64(r.r,"event.r")}), ...(r.o===undefined?{}:{o:uint64(r.o,"event.o")}), ...(r.p===undefined?{}:{p:uint64(r.p,"event.p")}), a:amount(r.a,"event.a"), b:amount(r.b,"event.b"), lb:amount(r.lb,"event.lb"), f:amount(r.f,"event.f"), ...(r.bfa===undefined?{}:{bfa:amount(r.bfa,"event.bfa")}) }; }
function stats(value: unknown): Row { const r=object(value,"account stats"); return { in:safeInteger(r.in,"stats.in",0xffffffff), id:uint64(r.id,"stats.id"), td:amount(r.td,"stats.td"), tw:amount(r.tw,"stats.tw"), tv:amount(r.tv,"stats.tv"), tf:amount(r.tf,"stats.tf"), ...(r.tbf===undefined?{}:{tbf:amount(r.tbf,"stats.tbf")}), trp:amount(r.trp,"stats.trp"), wr:safeInteger(r.wr,"stats.wr"), tt:safeInteger(r.tt,"stats.tt") }; }
function order(value: unknown): Row { const r=object(value,"order"); return { ...r, at:timestamp(r.at,"order.at"), c:timestamp(r.c,"order.c"), rq:uint64(r.rq,"order.rq"), mkt:safeInteger(r.mkt,"order.mkt",0xffffffff), acc:uint64(r.acc,"order.acc"), oid:uint64(r.oid,"order.oid"), scid:uint64(r.scid,"order.scid"), st:safeInteger(r.st,"order.st"), sr:safeInteger(r.sr,"order.sr"), t:safeInteger(r.t,"order.t"), ...(r.r===undefined?{}:{r:bool(r.r,"order.r")}), ...(r.p===undefined?{}:{p:uint64(r.p,"order.p")}), os:uint64(r.os,"order.os"), fp:uint64(r.fp,"order.fp"), fs:uint64(r.fs,"order.fs"), f:amount(r.f,"order.f"), ...(r.bfa===undefined?{}:{bfa:amount(r.bfa,"order.bfa")}), ...(r.tif===undefined?{}:{tif:uint64(r.tif,"order.tif")}), fl:safeInteger(r.fl,"order.fl"), ...(r.tp===undefined?{}:{tp:uint64(r.tp,"order.tp")}), ...(r.lp===undefined?{}:{lp:uint64(r.lp,"order.lp")}), mm:safeInteger(r.mm,"order.mm"), lv:safeInteger(r.lv,"order.lv") }; }
function fill(value: unknown): Row { const r=object(value,"fill"); return { ...r, at:timestamp(r.at,"fill.at"), mkt:safeInteger(r.mkt,"fill.mkt",0xffffffff), acc:uint64(r.acc,"fill.acc"), oid:uint64(r.oid,"fill.oid"), t:safeInteger(r.t,"fill.t"), l:safeInteger(r.l,"fill.l"), ...(r.p===undefined?{}:{p:uint64(r.p,"fill.p")}), s:uint64(r.s,"fill.s"), f:amount(r.f,"fill.f"), ...(r.bfa===undefined?{}:{bfa:amount(r.bfa,"fill.bfa")}) }; }
function position(value: unknown): Row { const r=object(value,"position"); return { ...r, at:timestamp(r.at,"position.at"), mkt:safeInteger(r.mkt,"position.mkt",0xffffffff), acc:uint64(r.acc,"position.acc"), pid:uint64(r.pid,"position.pid"), rq:uint64(r.rq,"position.rq"), oid:uint64(r.oid,"position.oid"), st:safeInteger(r.st,"position.st"), sr:safeInteger(r.sr,"position.sr"), sd:safeInteger(r.sd,"position.sd"), c:amount(r.c,"position.c"), ep:uint64(r.ep,"position.ep"), ...(r.epr===undefined?{}:{epr:safeInteger(r.epr,"position.epr")}), s:uint64(r.s,"position.s"), fee:amount(r.fee,"position.fee"), efs:signedInteger(r.efs,"position.efs"), lv:safeInteger(r.lv,"position.lv"), ...(r.dpnl===undefined?{}:{dpnl:amount(r.dpnl,"position.dpnl")}), ...(r.fnd===undefined?{}:{fnd:amount(r.fnd,"position.fnd")}), ...(r.xp===undefined?{}:{xp:uint64(r.xp,"position.xp")}), xfs:signedInteger(r.xfs,"position.xfs"), ots:timestamp(r.ots,"position.ots"), ...(r.e===undefined?{}:{e:array(r.e,"position.e").map(position)}) }; }

export function mapAuthenticatedFrame(value: unknown): PerplAuthenticatedFrame {
  const r=object(value,"authenticated frame"); const mt=safeInteger(r.mt,"mt");
  switch(mt){
    case 19:return { ...r, mt, sn:uint64(r.sn,"wallet.sn"), at:timestamp(r.at,"wallet.at"), addr:string(r.addr,"wallet.addr"), n:uint64(r.n,"wallet.n"), fl:safeInteger(r.fl,"wallet.fl"), ...(r.as===undefined?{}:{as:array(r.as,"wallet.as").map(account)}), ...(r.sts===undefined?{}:{sts:array(r.sts,"wallet.sts").map(stats)}) } as unknown as PerplAuthenticatedFrame;
    case 20:return { ...r, mt, at:timestamp(r.at,"wallet.at"), addr:string(r.addr,"wallet.addr"), n:uint64(r.n,"wallet.n"), fl:safeInteger(r.fl,"wallet.fl") } as unknown as PerplAuthenticatedFrame;
    case 21:return {mt,...account(r)} as unknown as PerplAuthenticatedFrame;
    case 22:return { ...r, mt, ...(r.sn===undefined?{}:{sn:uint64(r.sn,"request.sn")}), rq:uint64(r.rq,"request.rq"), mkt:safeInteger(r.mkt,"request.mkt",0xffffffff), acc:uint64(r.acc,"request.acc"), ...(r.oid===undefined?{}:{oid:uint64(r.oid,"request.oid")}), t:safeInteger(r.t,"request.t"), ...(r.p===undefined?{}:{p:uint64(r.p,"request.p")}), s:uint64(r.s,"request.s"), ...(r.a===undefined?{}:{a:amount(r.a,"request.a")}), ...(r.tif===undefined?{}:{tif:uint64(r.tif,"request.tif")}), fl:safeInteger(r.fl,"request.fl"), ...(r.tp===undefined?{}:{tp:uint64(r.tp,"request.tp")}), ...(r.tr===undefined?{}:{tr:uint64(r.tr,"request.tr")}), ...(r.lp===undefined?{}:{lp:uint64(r.lp,"request.lp")}), lv:safeInteger(r.lv,"request.lv"), lb:uint64(r.lb,"request.lb") } as unknown as PerplAuthenticatedFrame;
    case 23:case 24:return { ...r, mt, at:timestamp(r.at,"orders.at"), d:array(r.d,"orders.d").map(order) } as unknown as PerplAuthenticatedFrame;
    case 25:return { ...r, mt, at:timestamp(r.at,"fills.at"), d:array(r.d,"fills.d").map(fill) } as unknown as PerplAuthenticatedFrame;
    case 26:case 27:return { ...r, mt, at:timestamp(r.at,"positions.at"), d:array(r.d,"positions.d").map(position) } as unknown as PerplAuthenticatedFrame;
    case 28:return {mt,...stats(r)} as unknown as PerplAuthenticatedFrame;
    case 29:return { mt, chain_id:uint64(r.chain_id,"signin.chain_id"), api_key:string(r.api_key,"signin.api_key"), timestamp:string(r.timestamp,"signin.timestamp"), nonce:string(r.nonce,"signin.nonce"), signature:string(r.signature,"signin.signature") };
    default:throw new ExchangeAdapterError(`Unsupported Perpl authenticated mt ${mt}`);
  }
}
