import { ExchangeAdapterError } from "../AdapterError.js";
import type { OrderSide, OrderType } from "../ExchangeAdapter.js";
import { scaledToNumber, timestampMs } from "./mappers.js";
import type { PerplAuthFill, PerplAuthOrder, PerplAuthSnapshotRaw, PerplAuthState, PerplAuthUpdateRaw, PerplBalance, PerplFundingEntry, PerplPnlEntry, PerplPosition, PerplScaling } from "./authTypes.js";

type Row = Record<string, unknown>;
const integer = /^-?\d+$/;
function row(value: unknown, label: string): Row { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ExchangeAdapterError(`Perpl authenticated ${label} is malformed`); return value as Row; }
function text(value: unknown, field: string): string { if (typeof value !== "string" || !value.trim()) throw new ExchangeAdapterError(`Perpl authenticated ${field} is malformed`); return value; }
function scaled(value: unknown, decimals: number, field: string): number { if (!integer.test(String(value))) throw new ExchangeAdapterError(`Perpl authenticated ${field} is malformed`); return scaledToNumber(String(value), decimals, field); }
function sequence(value: unknown): bigint { if (!/^\d+$/.test(String(value))) throw new ExchangeAdapterError("Perpl authenticated sn is malformed"); const result = BigInt(String(value)); if (result > BigInt(Number.MAX_SAFE_INTEGER)) throw new ExchangeAdapterError("Perpl authenticated sn is unsafe"); return result; }
function exactKeys(value: Row, required: readonly string[], optional: readonly string[] = []): void { const allowed = new Set([...required, ...optional]); if (required.some((key) => !(key in value)) || Object.keys(value).some((key) => !allowed.has(key))) throw new ExchangeAdapterError("Perpl authenticated payload schema mismatch"); }
function side(value: unknown): OrderSide { if (value === 1 || value === "buy") return "buy"; if (value === 2 || value === "sell") return "sell"; throw new ExchangeAdapterError("Perpl authenticated order side is malformed"); }
function orderType(value: unknown): OrderType { const types: Record<string, OrderType> = { limit: "limit", post_only: "postOnly", ioc: "immediateOrCancel", fok: "fillOrKill" }; const result = types[String(value)]; if (!result) throw new ExchangeAdapterError("Perpl authenticated order type is malformed"); return result; }
function status(value: unknown): PerplAuthOrder["status"] { if (["open", "filled", "cancelled", "rejected"].includes(String(value))) return String(value) as PerplAuthOrder["status"]; throw new ExchangeAdapterError("Perpl authenticated order status is malformed"); }

function mapBalance(value: unknown, scale: PerplScaling): PerplBalance { const r=row(value,"balance"); exactKeys(r,["asset","total","available"]); return { asset:text(r.asset,"balance.asset"), total:scaled(r.total,scale.collateralDecimals??6,"balance.total"), available:scaled(r.available,scale.collateralDecimals??6,"balance.available") }; }
function mapPosition(value: unknown, scale: PerplScaling): PerplPosition { const r=row(value,"position"); exactKeys(r,["market_id","base_size","entry_price","mark_price","unrealized_pnl"]); return { marketId:text(r.market_id,"position.market_id"), baseSize:scaled(r.base_size,scale.sizeDecimals,"position.base_size"), entryPrice:scaled(r.entry_price,scale.priceDecimals,"position.entry_price"), markPrice:scaled(r.mark_price,scale.priceDecimals,"position.mark_price"), unrealizedPnl:scaled(r.unrealized_pnl,scale.collateralDecimals??6,"position.unrealized_pnl") }; }
function mapOrder(value: unknown, scale: PerplScaling): PerplAuthOrder { const r=row(value,"order"); exactKeys(r,["order_id","market_id","side","type","price","size","filled_size","status"],["client_order_id"]); const size=scaled(r.size,scale.sizeDecimals,"order.size"), filledSize=scaled(r.filled_size,scale.sizeDecimals,"order.filled_size"); const rawSize=BigInt(String(r.size)), rawFilled=BigInt(String(r.filled_size)); if (rawFilled < 0n || rawFilled > rawSize) throw new ExchangeAdapterError("Perpl authenticated order fill exceeds size"); return { orderId:text(r.order_id,"order.order_id"), ...(r.client_order_id === undefined ? {} : { clientOrderId:text(r.client_order_id,"order.client_order_id") }), marketId:text(r.market_id,"order.market_id"), side:side(r.side), type:orderType(r.type), price:scaled(r.price,scale.priceDecimals,"order.price"), size, filledSize, remainingSize:scaled(rawSize-rawFilled,scale.sizeDecimals,"order.remaining_size"), status:status(r.status) }; }
function mapFill(value: unknown, scale: PerplScaling): PerplAuthFill { const r=row(value,"fill"); exactKeys(r,["fill_id","order_id","market_id","price","size","fee","timestamp"]); return { fillId:text(r.fill_id,"fill.fill_id"), orderId:text(r.order_id,"fill.order_id"), marketId:text(r.market_id,"fill.market_id"), price:scaled(r.price,scale.priceDecimals,"fill.price"), size:scaled(r.size,scale.sizeDecimals,"fill.size"), fee:scaled(r.fee,scale.collateralDecimals??6,"fill.fee"), timestamp:timestampMs(r.timestamp,"fill.timestamp") }; }
function mapPnl(value: unknown, scale: PerplScaling): PerplPnlEntry { const r=row(value,"pnl"); exactKeys(r,["id","market_id","amount","timestamp"]); return { id:text(r.id,"pnl.id"), marketId:text(r.market_id,"pnl.market_id"), amount:scaled(r.amount,scale.collateralDecimals??6,"pnl.amount"), timestamp:timestampMs(r.timestamp,"pnl.timestamp") }; }
function mapFunding(value: unknown, scale: PerplScaling): PerplFundingEntry { const r=row(value,"funding"); exactKeys(r,["id","market_id","amount","rate","timestamp"]); return { id:text(r.id,"funding.id"), marketId:text(r.market_id,"funding.market_id"), amount:scaled(r.amount,scale.collateralDecimals??6,"funding.amount"), rate:scaled(r.rate,6,"funding.rate"), timestamp:timestampMs(r.timestamp,"funding.timestamp") }; }

export function mapAuthSnapshot(raw: PerplAuthSnapshotRaw, scale: PerplScaling): PerplAuthState {
  const r=row(raw,"snapshot"); exactKeys(r,["mt","sn","balances","positions","orders","fills","pnl","funding"]); if(r.mt!=="snapshot") throw new ExchangeAdapterError("Perpl authenticated snapshot type is malformed");
  return { sequence:sequence(r.sn), balances:raw.balances.map((v)=>mapBalance(v,scale)), positions:raw.positions.map((v)=>mapPosition(v,scale)), orders:raw.orders.map((v)=>mapOrder(v,scale)), fills:raw.fills.map((v)=>mapFill(v,scale)), pnl:raw.pnl.map((v)=>mapPnl(v,scale)), funding:raw.funding.map((v)=>mapFunding(v,scale)) };
}

export function mapAuthUpdate(raw: PerplAuthUpdateRaw, scale: PerplScaling): Partial<Omit<PerplAuthState,"sequence">> & { sequence: bigint } {
  const r=row(raw,"update"); exactKeys(r,["mt","sn"],["balances","positions","orders","fills","pnl","funding"]); if(r.mt!=="update") throw new ExchangeAdapterError("Perpl authenticated update type is malformed");
  const mapped: Partial<Omit<PerplAuthState,"sequence">> & { sequence: bigint }={sequence:sequence(r.sn)};
  if(raw.balances) mapped.balances=raw.balances.map((v)=>mapBalance(v,scale)); if(raw.positions) mapped.positions=raw.positions.map((v)=>mapPosition(v,scale)); if(raw.orders) mapped.orders=raw.orders.map((v)=>mapOrder(v,scale)); if(raw.fills) mapped.fills=raw.fills.map((v)=>mapFill(v,scale)); if(raw.pnl) mapped.pnl=raw.pnl.map((v)=>mapPnl(v,scale)); if(raw.funding) mapped.funding=raw.funding.map((v)=>mapFunding(v,scale)); return mapped;
}
